version: "3"
services:
  human:
    image: human-docker
    ports:
      - "8080:8080"
    networks:
      - peopleToDoList
    depends_on:
      - todolist

  todolist:
    image: docker-spring-boot
    ports:
      - "5000:5000"
    networks:
      - peopleToDoList

networks:
  peopleToDoList: